# Generated by Django 4.0.3 on 2022-06-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_note_date_time_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_time_field',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contact', to='contacts.contact'),
        ),
    ]
