# Generated by Django 4.0.3 on 2022-06-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_note_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='text_field',
        ),
    ]
